apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
  - secretName: k8s-secret
    type: Opaque
    data:
    - objectName: DB_USER
      key: db_user
    - objectName: DB_PASSWORD
      key: db_password
    - objectName: DB_HOST
      key: db_host
    - objectName: DB_NAME
      key: db_name
  parameters:     
    objects: | 
      - objectName: luna-cluster
        objectType: secretsmanager
        jmesPath:
          - path: DB_USER
            objectAlias: DB_USER
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
          - path: DB_HOST
            objectAlias: DB_HOST
          - path: DB_NAME
            objectAlias: DB_NAME
