apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: luna-cluster
  region: us-east-1

nodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
